In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('sentiment_tweets3.csv')

In [3]:
data.head()

Unnamed: 0                                            message  label
0         106  just had a real good moment. i missssssssss hi...      0
1         217         is reading manga  http://plurk.com/p/mzp1e      0
2         220  @comeagainjen http://twitpic.com/2y2lx - http:...      0
3         288  @lapcat Need to send 'em to my accountant tomo...      0
4         540      ADD ME ON MYSPACE!!!  myspace.com/LookThunder      0

In [5]:
y=data['label']

In [13]:
y.value_counts()

0    8000
1    2314
Name: label, dtype: int64

In [14]:
x=data['message']

In [15]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [16]:
tokenizer=Tokenizer(num_words=5000,oov_token='<oov>')
tokenizer.fit_on_texts(x)
word_index=tokenizer.word_index
sequences=tokenizer.texts_to_sequences(x)
padded=pad_sequences(sequences,maxlen=60,padding='post',truncating='post')

In [17]:
print(padded)

[[  22   91    5 ...    0    0    0]
 [  11  547    1 ...    0    0    0]
 [3570   27  176 ...    0    0    0]
 ...
 [2493 4497 2321 ...    0    0    0]
 [ 317 1804    5 ...    0    0    0]
 [ 659    0    0 ...    0    0    0]]


In [18]:
print(word_index)

{'<oov>': 1, 'i': 2, 'to': 3, 'the': 4, 'a': 5, 'and': 6, 'depression': 7, 'you': 8, 'my': 9, 'of': 10, 'is': 11, 'it': 12, 'for': 13, 'in': 14, 'with': 15, 'that': 16, 'on': 17, 'me': 18, 'have': 19, 'com': 20, 'so': 21, 'just': 22, "i'm": 23, 'be': 24, 'your': 25, 'but': 26, 'http': 27, 'good': 28, 'are': 29, 'this': 30, 'was': 31, 'twitter': 32, 'not': 33, 'at': 34, 'day': 35, 'out': 36, 'love': 37, 'like': 38, 'all': 39, 'up': 40, 'now': 41, 'get': 42, 'about': 43, "it's": 44, 'from': 45, 'can': 46, 'https': 47, 'do': 48, 'what': 49, 'quot': 50, 'lol': 51, 'time': 52, 'know': 53, 'anxiety': 54, 'will': 55, 'if': 56, 'we': 57, 'go': 58, 'going': 59, 'u': 60, 'today': 61, 'how': 62, 'thanks': 63, 'emoji': 64, 'no': 65, 'or': 66, 'one': 67, "don't": 68, 'as': 69, 'when': 70, 'more': 71, 'some': 72, 'got': 73, 'great': 74, 'see': 75, 'pic': 76, 'new': 77, 'too': 78, 'am': 79, 'back': 80, 'well': 81, 'has': 82, 'amp': 83, 'an': 84, 'think': 85, 'by': 86, 'www': 87, 'there': 88, 'really'

In [19]:
import tensorflow as tf

In [20]:
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(5000,15,input_length=60),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(10,activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

In [21]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 60, 15)            75000     
_________________________________________________________________
bidirectional (Bidirectional (None, 128)               40960     
_________________________________________________________________
dense (Dense)                (None, 10)                1290      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 117,261
Trainable params: 117,261
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.fit(padded,y,epochs=10)

Train on 10314 samples
Epoch 1/10
10314/10314 [==============================] - 11s 1ms/sample - loss: 0.2652 - accuracy: 0.8987
Epoch 2/10
10314/10314 [==============================] - 10s 923us/sample - loss: 0.0138 - accuracy: 0.9976
Epoch 3/10
10314/10314 [==============================] - 10s 953us/sample - loss: 0.0094 - accuracy: 0.9985
Epoch 4/10
10314/10314 [==============================] - 10s 950us/sample - loss: 0.0058 - accuracy: 0.9989
Epoch 5/10
10314/10314 [==============================] - 10s 1ms/sample - loss: 0.0048 - accuracy: 0.9990
Epoch 6/10
10314/10314 [==============================] - 10s 947us/sample - loss: 0.0039 - accuracy: 0.9992
Epoch 7/10
10314/10314 [==============================] - 10s 965us/sample - loss: 0.0041 - accuracy: 0.9993
Epoch 8/10
10314/10314 [==============================] - 11s 1ms/sample - loss: 0.0027 - accuracy: 0.9995
Epoch 9/10
10314/10314 [==============================] - 10s 1ms/sample - loss: 0.0024 - accuracy: 0.9997
Epoc

In [27]:
model.predict(['i am so sad'])

ValueError: Error when checking input: expected embedding_input to have shape (60,) but got array with shape (1,)